apiVersion: v1
kind: Secret
metadata:
  name: genesis-secrets
type: Opaque
data:
  database_url: cG9zdGdyZXNxbDovL2dlbmVzaXM6Z2VuZXNpc0Bwb3N0Z3JlczoxMjM0L2dlbmVzaXM=
  redis_url: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=
  api_key_id: bG9jYWwtYWRtaW4=
  api_key_secret: bG9jYWwtc2VjcmV0
