"""Prometheus metric definitions for the Genesis kernel."""
from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram

# Reflexive intelligence metrics.
genesis_reflexive_cycles_total = Counter(
    "genesis_reflexive_cycles_total",
    "Total number of reflexive intelligence cycles executed.",
)

genesis_simulations_total = Counter(
    "genesis_simulations_total",
    "Simulation executions within the reflexive intelligence layer.",
    labelnames=("status",),
)

genesis_reflection_confidence_mean = Gauge(
    "genesis_reflection_confidence_mean",
    "Rolling mean confidence recorded in reflection logs.",
)

genesis_uncertainty_metrics_total = Gauge(
    "genesis_uncertainty_metrics_total",
    "Number of metrics tracked by the uncertainty engine.",
)

genesis_twin_sync_latency_seconds = Histogram(
    "genesis_twin_sync_latency_seconds",
    "Latency required to construct or refresh the digital twin.",
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0),
)

genesis_meta_anomalies_total = Counter(
    "genesis_meta_anomalies_total",
    "Anomalies detected by reflexive introspection.",
)

# Histogram tracking the duration of each evaluator execution.
genesis_eval_duration_seconds = Histogram(
    "genesis_eval_duration_seconds",
    "Time spent running module evaluations via the AutoTest service.",
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)

# Gauge capturing the latest score emitted for a module variant.
genesis_module_score = Gauge(
    "genesis_module_score",
    "Composite reward score per module variant.",
    labelnames=("module", "version"),
)

# Counter recording module replacement events triggered by the optimizer.
genesis_replacements_total = Counter(
    "genesis_replacements_total",
    "Number of times the optimizer promoted a new module implementation.",
)

# Router selection counter capturing policy decisions.
genesis_router_selection_total = Counter(
    "genesis_router_selection_total",
    "Router selections per policy and module variant.",
    labelnames=("policy", "module", "version"),
)

# Canary rollout counters.
genesis_canary_promotions_total = Counter(
    "genesis_canary_promotions_total",
    "Successful canary promotions per module version.",
    labelnames=("module", "version"),
)

genesis_canary_rollbacks_total = Counter(
    "genesis_canary_rollbacks_total",
    "Number of canary rollbacks triggered by SLO breaches.",
    labelnames=("module", "version", "reason"),
)

# Traffic share gauge for observability dashboards.
genesis_traffic_share = Gauge(
    "genesis_traffic_share",
    "Current traffic share per module version.",
    labelnames=("module", "version"),
)

# RL reward telemetry.
genesis_rl_reward = Gauge(
    "genesis_rl_reward",
    "Latest reward emitted by the online optimizer.",
    labelnames=("module", "version"),
)

genesis_rl_update_total = Counter(
    "genesis_rl_update_total",
    "Number of optimizer updates processed.",
)

# Cache and rate-limit instrumentation.
genesis_cache_hits_total = Counter(
    "genesis_cache_hits_total",
    "Cache hits recorded per task type.",
    labelnames=("task_type",),
)

genesis_rate_limit_drops_total = Counter(
    "genesis_rate_limit_drops_total",
    "Requests dropped because of rate limiting per task type.",
    labelnames=("task_type",),
)

# Orchestration decision latency histogram.
genesis_orch_decision_duration_seconds = Histogram(
    "genesis_orch_decision_duration_seconds",
    "Time spent computing orchestration decisions (routing, canary, optimizer).",
    buckets=(
        0.001,
        0.005,
        0.01,
        0.025,
        0.05,
        0.1,
        0.25,
        0.5,
        1.0,
    ),
)

# Cluster metrics
genesis_cluster_nodes_total = Gauge(
    "genesis_cluster_nodes_total",
    "Total number of nodes registered in the Genesis cluster.",
)

genesis_cluster_heartbeat_lag_seconds = Gauge(
    "genesis_cluster_heartbeat_lag_seconds",
    "Seconds since the last heartbeat was received for each node.",
    labelnames=("node_id",),
)

genesis_provenance_edges_total = Counter(
    "genesis_provenance_edges_total",
    "Total number of provenance edges recorded.",
)

genesis_policy_violations_total = Counter(
    "genesis_policy_violations_total",
    "Total number of policy violations detected by governance.",
)

genesis_replay_runs_total = Counter(
    "genesis_replay_runs_total",
    "Number of replay operations executed.",
)

genesis_signature_verifications_total = Counter(
    "genesis_signature_verifications_total",
    "Number of signature verification events.",
    labelnames=("status",),
)

# Cognitive research instrumentation.
genesis_experiments_total = Counter(
    "genesis_experiments_total",
    "Number of experiments executed by the cognition stack.",
    labelnames=("status",),
)

genesis_hypotheses_generated_total = Counter(
    "genesis_hypotheses_generated_total",
    "Number of experiment hypotheses generated by the planner.",
)

genesis_insights_total = Counter(
    "genesis_insights_total",
    "Insights derived from automated research.",
)

genesis_reasoner_latency_seconds = Histogram(
    "genesis_reasoner_latency_seconds",
    "Latency of cognition reasoner responses.",
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5),
)

genesis_theorist_updates_total = Counter(
    "genesis_theorist_updates_total",
    "Theorist update invocations.",
)

genesis_publications_total = Counter(
    "genesis_publications_total",
    "Number of research publications exported.",
)

genesis_knowledge_nodes_total = Gauge(
    "genesis_knowledge_nodes_total",
    "Number of nodes tracked in the knowledge graph.",
)

# Civilization layer instrumentation.
genesis_federation_peers_total = Gauge(
    "genesis_federation_peers_total",
    "Total number of peers registered in the federation mesh.",
)

genesis_consensus_rounds_total = Counter(
    "genesis_consensus_rounds_total",
    "Number of consensus rounds executed by the federation.",
    labelnames=("state",),
)

genesis_economy_tx_total = Counter(
    "genesis_economy_tx_total",
    "Economy ledger transactions grouped by reason.",
    labelnames=("reason",),
)

genesis_ethics_violations_total = Counter(
    "genesis_ethics_violations_total",
    "Ethics violations detected by the civilization auditor.",
    labelnames=("principle",),
)

genesis_replica_boots_total = Counter(
    "genesis_replica_boots_total",
    "Replica bootstrap operations executed across the federation.",
)

genesis_self_repair_events_total = Counter(
    "genesis_self_repair_events_total",
    "Self repair events triggered by lifecycle management.",
)

__all__ = [
    "genesis_eval_duration_seconds",
    "genesis_module_score",
    "genesis_replacements_total",
    "genesis_router_selection_total",
    "genesis_canary_promotions_total",
    "genesis_canary_rollbacks_total",
    "genesis_traffic_share",
    "genesis_rl_reward",
    "genesis_rl_update_total",
    "genesis_cache_hits_total",
    "genesis_rate_limit_drops_total",
    "genesis_orch_decision_duration_seconds",
    "genesis_cluster_nodes_total",
    "genesis_cluster_heartbeat_lag_seconds",
    "genesis_provenance_edges_total",
    "genesis_policy_violations_total",
    "genesis_replay_runs_total",
    "genesis_signature_verifications_total",
    "genesis_experiments_total",
    "genesis_hypotheses_generated_total",
    "genesis_insights_total",
    "genesis_reasoner_latency_seconds",
    "genesis_theorist_updates_total",
    "genesis_publications_total",
    "genesis_knowledge_nodes_total",
    "genesis_federation_peers_total",
    "genesis_consensus_rounds_total",
    "genesis_economy_tx_total",
    "genesis_ethics_violations_total",
    "genesis_replica_boots_total",
    "genesis_self_repair_events_total",
    "genesis_reflexive_cycles_total",
    "genesis_simulations_total",
    "genesis_reflection_confidence_mean",
    "genesis_uncertainty_metrics_total",
    "genesis_twin_sync_latency_seconds",
    "genesis_meta_anomalies_total",
]

